### ISSUE TITLE
リンクが切れているかもしれません。

### ISSUE THREAD

**Issue by TaizenK** [unchain-dev/UNCHAIN-projects#127]
## 提案内容
SOLANA DAPP の Section2 Lesson1、Anchorをインストールする際の説明文中にあるAnchorのリンクですが、クリックすると404ページとなります。リンクが切れているかもしれません。

## 備考
該当場所gyazoで撮りました。

https://gyazo.com/6f57638b03c5755ed078e7e32d8dd8b0

**Comment by yukis4san** [comment]
ありがとうございます！
リンクこちらに差し替えました！反映お願いします! @neila
https://hackmd.io/@ironaddicteddog/solana-anchor-escrow

**Comment by neila** [comment]
@yukis4san 

こちらリンク確認しましたが `This document is not maintained anymore. Please visit our new [book](https://book.solmeet.dev/notes/intro-to-anchor) for the latest update.` と記載があります。可能な限りofficial linkを用いるように心がけてください！再度差し替えお願いします (また、こういうことがあるので繰り返しになりますがmain直接じゃなくてブランチ切ってPR出してください 🙇 )
