### ISSUE TITLE
文章が抜けていると思われます

### ISSUE THREAD

**Issue by TaizenK** [unchain-dev/UNCHAIN-projects#128]
## 提案内容
SOLANA NFT DROP
Section0 Lesson1 
「本プロジェクトは下記の３つのステップに分かれています。」の下記の部分が抜け落ちていると思われます。
## 備考
該当部分gyazoで撮りました。

https://gyazo.com/2487e800c296f00577d31d0ed9e893ba

**Comment by neila** [comment]
すみません、こちらgyazoのリンクが404になってしまい確認することができませんでした... 
修正PRを別途出し、こちらのissueをメンションいただけますか？

**Comment by TaizenK** [comment]
@neila さん

まことに恥ずかしい限りですが、
「issueをメンションする」と言われますのはこのように「＠＋宛名でコメントを送る」という意味でよろしかったでしょうか。

Pull request は先ほど投稿いたしました。
よろしくお願い申し上げます。
