### ISSUE TITLE
文章の重複

### ISSUE THREAD

**Issue by TaizenK** [unchain-dev/UNCHAIN-projects#132]
## 提案内容
すいません。もう1つ見つかりました。
SOLANA ONLINE STORE 最後の部分で文章が重複しています。
上の文のairtableのリンクを押すと関係の無いところへ飛びます。

## 背景
リンクを押したところ、ページ上部へ飛んだので気がつきました。

## 備考
VScodeで該当する部分を開けてみましたが、文章は1度しか書かれておらず、原因はわかりませんでした。

該当部分gyazoにて撮りました。
https://gyazo.com/b6c7a046df94f952531d09af26dd7fad

**Comment by neila** [comment]
@yukis4san これairtableの文言はフロントエンドで自動挿入しているのでmarkdownに記述する必要はないです！修正お願いします 🙏
