### ISSUE TITLE
SolidityのVersion表示について

### ISSUE THREAD

**Issue by Tatyy555** [unchain-dev/UNCHAIN-projects#157]
## 提案内容
102-ETH-NFT-Collectionのsection-2-Lesson-3について、
中盤のMyEpicNFT.solのコード内容について、
`pragma solidity 0.8.9;`
と記載されておりますが、エラーが出ました。

前述のコードを参考に、以下と思います。
`pragma solidity ^0.8.9;`

細かいですがご確認いただけると幸いです。

## 備考

https://unchain-portal.netlify.app/projects/102-ETH-NFT-Collection/section-2-Lesson-3

section-4-Lesson-1のMyEpicNFT.solも同様に” ^ ”が抜けているようです。
https://unchain-portal.netlify.app/projects/102-ETH-NFT-Collection/section-4-Lesson-1

**Comment by neila** [comment]
ありがとうございます。是非こちらの変更点を修正したPRを送ってください！ 🙇🏽

**Comment by Tatyy555** [comment]
承知しました！やってみます！
