### ISSUE TITLE
`public/images/` 下が規格化されていない

### ISSUE THREAD

**Issue by neila** [unchain-dev/UNCHAIN-projects#171]
ETH-NFT-Makerなどバナー画像がそもそも存在しないプロジェクトがある。
また、`section-0`なのか`README`なのかの命名が一貫していない。

修正お願いします 🙏🏽 
修正は別ブランチにpushの後PRお願いします

@KatotenMk2 @yukis4san

**Comment by neila** [comment]
ブランチ統合で地獄を起こさないように、`git pull -p`でまず最新状態をローカルに持ってきて、fix-dirから新しいブランチを切って作業することを強く推奨します

**Comment by yukis4san** [comment]
ETH-NFT-Makerなどバナー画像がそもそも存在しないプロジェクトがある。
また、section-0なのかREADMEなのかの命名が一貫していない。
> UNCHAIN-projects/public/lean-bannerに全てのバナーを格納しました（READMEディレクトリはわかりにくいので消しました）。
![image](https://user-images.githubusercontent.com/13631648/190840041-8fbadded-c253-45be-8927-1dee1631eaff.png)

**Comment by neila** [comment]
`public/metadata/{CONTENT_TITLE}/banner.png`
にそれぞれ格納お願いします

**Comment by neila** [comment]
#177 でclose
