### ISSUE TITLE
画象と文字の間が空いている問題

### ISSUE THREAD

**Issue by yukis4san** [unchain-dev/UNCHAIN-projects#206]
## 提案内容
画象と文字の間が空いている問題

## 背景
学習画面を見ていたら、画象と文字が大きく空いている（全ての箇所）ので、お手隙の際に詰めていただけると幸いです。
VisualStudioで見たら、文字と画像の間は空白が無かったので、フロントエンド側で調整いただけるとありがたいです！

## 備考

例：https://app.unchain.tech/learn/Polygon-Generative-NFT/section-1_lesson-1

![image](https://user-images.githubusercontent.com/13631648/198826553-7b22d5b2-566d-4ca7-917a-f4fdaae3876c.png)
<img width="652" alt="image" src="https://user-images.githubusercontent.com/13631648/198826599-9ab668a2-d08b-4d0c-a286-3ae3289691bc.png">

**Comment by neila** [comment]
Issue irrelevant to this repository.
raise it [here](https://github.com/shiftbase-inc/UNCHAIN-Portal-frontend) instead
