### ISSUE TITLE
[URGENT] レッスンの中身漏れ

### ISSUE THREAD

**Issue by neila** [unchain-dev/UNCHAIN-projects#208]
## 提案内容
ETH DAOの

- S3L3
- S3L4

の中身がない

## 背景
n/a

## 備考
至急、直接PR送ってください

https://main.d3b382wqjpfut1.amplifyapp.com/learn/ETH-DAO/section-3_lesson-3
https://main.d3b382wqjpfut1.amplifyapp.com/learn/ETH-DAO/section-3_lesson-4

n/a

**Comment by neila** [comment]
@KatotenMk2 こちら対応お願いします 🙏🏽

**Comment by KatotenMk2** [comment]
@neila 
漏れあったようで申し訳ないです・・・！
今ほど対応しましたのでご確認お願いします！

**Comment by naoyo4** [comment]
Solana-dApp　Section 1　Lesson 1

[Phantom Walletを設定しよう！](https://app.unchain.tech/learn/Solana-dApp/section-1_lesson-1)

が無くなってしまってます。昨日までは、あったように思います。
（　GitHub 慣れてないので、ここへのコメントでいいのか分かりませんが・・・）
