### ISSUE TITLE
Solana-dApp　Section 1　Lesson 1　が昨日の  #208 関連で無くなっています？

### ISSUE THREAD

**Issue by naoyo4** [unchain-dev/UNCHAIN-projects#210]
Solana-dApp　Section 1　Lesson 1

[Phantom Walletを設定しよう！](https://app.unchain.tech/learn/Solana-dApp/section-1_lesson-1)

が無くなってしまってます。昨日までは、あったように思います。
（　GitHub 慣れてないので、ここへのコメントでいいのか、このコメントが正しいのか分かりませんが取り急ぎ・・・）

**Comment by neila** [comment]
fixed in 1d60340e9553c7b84bbb0d62eace90c08dd1de16
