### ISSUE TITLE
PhantomWalletのネットワーク設定

### ISSUE THREAD

**Issue by Akihi-Sumi** [unchain-dev/UNCHAIN-projects#215]
## 提案内容
PhantomWalletの最初の設定で、Devnetに変更する際、  
「設定」→「デベロッパー設定」→「ネットワークの変更」→「DevNet」  
のように、「デベロッパー設定」を挟みますので、テキストの確認をお願いします。

**Comment by neila** [comment]
ありがとうございます！こちらよろしければ是非変更のPull Requestを送ってみてください！
