### ISSUE TITLE
imgurリンク→CID変更時について

### ISSUE THREAD

**Issue by sheegull** [unchain-dev/UNCHAIN-projects#234]
## 提案内容
ETH-NFT-Game Section4 Lesson2 
imgurリンクをCIDに変更する際、run.jsだけではなくdeploy.jsにも変更する説明をいれたほうがより丁寧だと感じました。

<img
 　src={`https://cloudflare-ipfs.com/ipfs/${characterNFT.imageURI}`}
 　alt={`Character ${characterNFT.name}`}
/>

Arena/index.jsなどで上記のようにsrcをipfs用リンクに変更しているので、
imgurの画像が表示しないエラーが発生します。

**Comment by KatotenMk2** [comment]
今ほど対応しました！
