### ISSUE TITLE
"Create NEAR App" テンプレート変更への対応

### ISSUE THREAD

**Issue by sheegull** [unchain-dev/UNCHAIN-projects#257]
## 内容
NEAR-Hotel-Booking-dApp Section3 Lesson1

以下のファイルが  ```near-hotel-booking-dapp / frontend``` に存在しません。

```
near-api.js
near-config.js
```

## 背景
インストールしたCreate NEAR Appのテンプレートがコンテンツ作成時のものと異なっている可能性がございます。

## 備考
Create NEAR App frontend template :
https://github.com/near/create-near-app/tree/master/templates/frontend

**Comment by sheegull** [comment]
# 追記
NEAR-Election-dApp で使用されていたver. 3.1.0がコンテンツ内のディレクトリ構成とかなり近しいと思います。

 ```npx create-near-app@3.1.0 --frontend=react --contract=rust near-election-dapp-frontend``` に変更

**Comment by neila** [comment]
@yk-saito こちらのissue、お手隙でreview & ご対応お願いします！:bow:
