### ISSUE TITLE
リンク先が見つからない

### ISSUE THREAD

**Issue by sheegull** [unchain-dev/UNCHAIN-projects#265]
## 提案内容
**NEAR-BikeShare Section2 Lesson2**

下記のリンク先が見つかりませんでした。

 - NEAR開発でのCargo.tomlの書き方 (https://docs.near.org/sdk/rust/building/basic-build)

**Comment by neila** [comment]
https://docs.near.org/sdk/rust/building/basics

こちらにリンク先が変わっているようですね

**Comment by sheegull** [comment]
対応ありがとうございます !!
