### ISSUE TITLE
リンク先が確認できません。

### ISSUE THREAD

**Issue by sheegull** [unchain-dev/UNCHAIN-projects#279]
## 提案内容
**AVAX-Messenger Section2 Lesson5【 ETHとAVAX 】**

下記のリンク先が確認できませんでした。

```
1ETH = 1AVA というわけではありません。
詳しくはこちら (https://docs.avax.network/specs/coreth-arc20s#nativeassetcall) をご覧ください。
```

**Comment by neila** [comment]
9月よりNative asset callがdeprecatedな模様ですね。
https://medium.com/avalancheavax/apricot-phase-6-native-asset-call-deprecation-a7b7a77b850a
@ryojiroakiyama 該当箇所の記述の修正よろしくお願いします :bow:
