### ISSUE TITLE
docs/ASTAR-SocialFi new fig 画像差し込み

### ISSUE THREAD

**Issue by kazuyukiy** [unchain-dev/UNCHAIN-projects#312]
## 提案内容
画像の新規差し込み
docs/ASTAR-SocialFi/ja/section-0/Lesson_2_環境構築をしよう.md
https://github.com/unchain-dev/UNCHAIN-projects/blob/main/docs/ASTAR-SocialFi/ja/section-0/Lesson_2_%E7%92%B0%E5%A2%83%E6%A7%8B%E7%AF%89%E3%82%92%E3%81%97%E3%82%88%E3%81%86.md?plain=1
の
// TODO default image of next.js
を新しい画像と差し替える。

266
-- // TODO default image of next.js
++\![]\(/public/images/ASTAR-SocialFi/section-0/0_2_14.png)

279
--![]\(/public/images/ASTAR-SocialFi/section-0/0_2_14.png)
++![]\(/public/images/ASTAR-SocialFi/section-0/0_2_15.png)

画像の番号の割り振りを下記のように変更
従来：
className 変更前の画像 none to 0_2_14.png 
className 変更後の画像 0_2_14.png to 0_2_15.png

新 0_2_14.png
![0_2_14](https://user-images.githubusercontent.com/92413399/215304307-d732775d-5123-446f-873d-5b6b265bd690.png)

新 0_2_15.png
![0_2_15](https://user-images.githubusercontent.com/92413399/215304316-daf85459-b679-4437-843b-f4972f478496.png)

**Comment by neila** [comment]
@kazuyukiy ありがとうございます！こちら是非PR出して直接修正してみてください！
https://docs.github.com/ja/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by kazuyukiy** [comment]
承知しました、PRします。

**Comment by kazuyukiy** [comment]
PRしました
