### ISSUE TITLE
ASTAR-SocialFi code might to be deleted

### ISSUE THREAD

**Issue by kazuyukiy** [unchain-dev/UNCHAIN-projects#315]
## 提案内容
コードの中で不要と思われる行

ASTAR-SocialFi/section-2_lesson-1

1)
postFunction.tsx
同じ if が二重になっている
761  if (output !== undefined && output !== null) 
762    if (output !== undefined && output !== null) 

2)
FT.tsx
使われていない変数　date
625 export const transfer = async (props: PropsTF) => {
630   const date = new Date();

647 export const distributeReferLikes = async (props: PropsDRL) => {
652   const date = new Date();

## 備考
コードの中身に関わることなので  Issue にしています。
妥当であれば、指示いただければPRします。

https://github.com/unchain-dev/UNCHAIN-projects/blob/main/docs/ASTAR-SocialFi/ja/section-2/Lesson_1_%E3%82%B3%E3%83%B3%E3%83%88%E3%83%A9%E3%82%AF%E3%83%88%E3%81%AE%E9%96%A2%E6%95%B0%E3%82%92%E5%91%BC%E3%81%B3%E5%87%BA%E3%81%9B%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%97%E3%82%88%E3%81%86.md?plain=1

**Comment by neila** [comment]
ありがとうございます。PRお願いします。

@honganji 来たらレビューお願いします

**Comment by kazuyukiy** [comment]
PRしました
